### PR TITLE
check null getImages function which is call on getPreview

### PR DESCRIPTION
**Pull request by VictorOffspring**
@karlsander @Kikobeats This one to fix the error on this issue #130 
Could you take a look. Thank you

### CODE REVIEW

**Comment by Kikobeats** [comment]
Thanks for this! I want to add a test over it, can you identify an URL that can fit for this case?

**Comment by VictorOffspring** [comment]
> Thanks for this! I want to add a test over it, can you identify an URL that can fit for this case?

@Kikobeats I guess it for all URL now because the api structure from Spotify has changed. From which I fetch using getData. Look at the "data.visualIdentity.image" property. Before it is "images" or "coverArt" (getImage function). I think it lead to this error.
```
{
  "type": "track",
  "name": "Immaterial",
  "uri": "spotify:track:5nTtCOCds6I0PHMNtqelas",
  "id": "5nTtCOCds6I0PHMNtqelas",
  "title": "Immaterial",
  "artists": [
    {
      "name": "SOPHIE",
      "uri": "spotify:artist:5a2w2tgpLwv26BYJf2qYwu"
    }
  ],
  "coverArt": null,
  "releaseDate": {
    "isoString": "2018-06-15T00:00:00Z"
  },
  "duration": 232806,
  "maxDuration": 232806,
  "isPlayable": true,
  "isExplicit": false,
  "audioPreview": {
    "url": "https://p.scdn.co/mp3-preview/2ed3e81fe7b79aca5ac655d89412d8ecb968423f"
  },
  "hasVideo": false,
  "relatedEntityUri": "spotify:artist:5a2w2tgpLwv26BYJf2qYwu",
  "visualIdentity": {
    "backgroundBase": {
      "alpha": 255,
      "blue": 97,
      "green": 73,
      "red": 104
    },
    "backgroundTintedBase": {
      "alpha": 255,
      "blue": 63,
      "green": 41,
      "red": 70
    },
    "textBase": {
      "alpha": 255,
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "textBrightAccent": {
      "alpha": 255,
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "textSubdued": {
      "alpha": 255,
      "blue": 222,
      "green": 195,
      "red": 232
    },
    "image": [
      {
        "url": "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e026b03d8c63599cc94263d7d60",
        "imageFormat": "JPEG",
        "maxHeight": 300,
        "maxWidth": 300
      },
      {
        "url": "https://image-cdn-ak.spotifycdn.com/image/ab67616d000048516b03d8c63599cc94263d7d60",
        "imageFormat": "JPEG",
        "maxHeight": 64,
        "maxWidth": 64
      },
      {
        "url": "https://image-cdn-ak.spotifycdn.com/image/ab67616d0000b2736b03d8c63599cc94263d7d60",
        "imageFormat": "JPEG",
        "maxHeight": 640,
        "maxWidth": 640
      }
    ]
  }
}
```

**Comment by VictorOffspring** [comment]
@Kikobeats I've just added new commit. Please run test again

**Comment by VictorOffspring** [comment]
@thangcqUET

**Pull request merged**
